GET https://extruct.iavian.net/proxy?url=https://www.dailywire.com/feeds/rss.xml

###
GET https://readability-go-production.up.railway.app/proxy?url=https://therightscoop.com/feed

###
GET http://localhost:8080/readability?url=https://www.thegatewaypundit.com/2026/01/tyrant-maduros-arrest-expect-cartel-ties-money-transfers/
